## Append samples you want in your CSV to this file as resources ##
resources:
- kubeeye_v1alpha1_clusterinsight.yaml
- kubeeyeplugins_v1alpha1_pluginsubscription.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
