{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "charts.fullname" . }}-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "charts.fullname" . }}-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ include "charts.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
{{- end }}