---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.1
  creationTimestamp: null
  name: inspectresults.kubeeye.kubesphere.io
spec:
  group: kubeeye.kubesphere.io
  names:
    kind: InspectResult
    listKind: InspectResultList
    plural: inspectresults
    singular: inspectresult
  scope: Cluster
  versions:
  - name: v1alpha2
    schema:
      openAPIV3Schema:
        description: InspectResult is the Schema for the inspectresults API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: InspectResultSpec defines the desired state of InspectResult
            properties:
              componentResult:
                items:
                  properties:
                    endpoint:
                      type: string
                    level:
                      type: string
                    name:
                      type: string
                    namespace:
                      type: string
                  type: object
                type: array
              inspectCluster:
                properties:
                  name:
                    type: string
                  provider:
                    type: string
                type: object
              inspectRuleTotal:
                additionalProperties:
                  type: integer
                type: object
              nodeInfoResult:
                additionalProperties:
                  properties:
                    commandResult:
                      items:
                        properties:
                          assert:
                            type: boolean
                          command:
                            type: string
                          level:
                            type: string
                          name:
                            type: string
                          value:
                            type: string
                        type: object
                      type: array
                    fileChangeResult:
                      items:
                        properties:
                          fileName:
                            type: string
                          issues:
                            items:
                              type: string
                            type: array
                          level:
                            type: string
                          path:
                            type: string
                        type: object
                      type: array
                    fileFilterResult:
                      items:
                        properties:
                          fileName:
                            type: string
                          issues:
                            items:
                              type: string
                            type: array
                          level:
                            type: string
                          path:
                            type: string
                        type: object
                      type: array
                    nodeInfo:
                      additionalProperties:
                        type: string
                      type: object
                    sysctlResult:
                      items:
                        properties:
                          assert:
                            type: boolean
                          level:
                            type: string
                          name:
                            type: string
                          value:
                            type: string
                        type: object
                      type: array
                    systemdResult:
                      items:
                        properties:
                          assert:
                            type: boolean
                          level:
                            type: string
                          name:
                            type: string
                          value:
                            type: string
                        type: object
                      type: array
                  type: object
                type: object
              opaResult:
                description: kubeeye inspect result
                properties:
                  extraInfo:
                    properties:
                      namespacesList:
                        items:
                          type: string
                        type: array
                      workloadsCount:
                        type: integer
                    type: object
                  percent:
                    type: integer
                  resourceResults:
                    items:
                      properties:
                        name:
                          type: string
                        namespace:
                          type: string
                        resourceType:
                          type: string
                        resultItems:
                          items:
                            properties:
                              level:
                                type: string
                              message:
                                type: string
                              reason:
                                type: string
                            type: object
                          type: array
                      type: object
                    type: array
                  scoreInfo:
                    properties:
                      dangerous:
                        type: integer
                      ignore:
                        type: integer
                      passing:
                        type: integer
                      score:
                        type: integer
                      total:
                        type: integer
                      warning:
                        type: integer
                    type: object
                type: object
              prometheusResult:
                items:
                  properties:
                    level:
                      type: string
                    result:
                      type: string
                  type: object
                type: array
            type: object
          status:
            description: InspectResultStatus defines the observed state of InspectResult
            properties:
              complete:
                type: boolean
              duration:
                type: string
              level:
                additionalProperties:
                  type: integer
                type: object
              policy:
                type: string
              taskEndTime:
                type: string
              taskStartTime:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
