---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: clusterinsights.kubeeye.kubesphere.io
spec:
  group: kubeeye.kubesphere.io
  names:
    kind: ClusterInsight
    listKind: ClusterInsightList
    plural: clusterinsights
    singular: clusterinsight
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ClusterInsight is the Schema for the clusterinsights API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ClusterInsightSpec defines the desired state of ClusterInsight
            properties:
              auditPeriod:
                type: string
            required:
            - auditPeriod
            type: object
          status:
            description: ClusterInsightStatus defines the observed state of ClusterInsight
            properties:
              auditPercent:
                type: integer
              auditResults:
                items:
                  properties:
                    namespace:
                      type: string
                    resultInfos:
                      items:
                        properties:
                          resourceInfos:
                            properties:
                              items:
                                items:
                                  properties:
                                    level:
                                      type: string
                                    message:
                                      type: string
                                    reason:
                                      type: string
                                  type: object
                                type: array
                              name:
                                type: string
                            type: object
                          resourceType:
                            type: string
                        type: object
                      type: array
                  type: object
                type: array
              clusterInfo:
                properties:
                  namespacesCount:
                    type: integer
                  namespacesList:
                    items:
                      type: string
                    type: array
                  nodesCount:
                    type: integer
                  version:
                    type: string
                  workloadsCount:
                    type: integer
                type: object
              lastScheduleTime:
                description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                  of cluster Important: Run "make" to regenerate code after modifying
                  this file'
                format: date-time
                type: string
              phase:
                type: string
              pluginsResults:
                items:
                  properties:
                    pluginName:
                      type: string
                    ready:
                      type: boolean
                    result:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                  type: object
                type: array
              scoreInfo:
                properties:
                  dangerous:
                    type: integer
                  ignore:
                    type: integer
                  passing:
                    type: integer
                  score:
                    type: integer
                  total:
                    type: integer
                  warning:
                    type: integer
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
