name: kind-test

on: [push, pull_request]

jobs:
  kind-test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - uses: actions/checkout@v2
      - name: Build KubeEye
        run: make ke
      - name: Creating kind cluster
        uses: helm/kind-action@v1.0.0-rc.1
      - name: Run KubeEye
        run: |
          rm -rf temp
          mkdir temp
          mv ke temp/
          ./temp/ke diag
